services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: memomate_app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=memomate_app
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "php", "artisan", "about"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  nginx:
    image: nginx:1.25-alpine
    container_name: memomate_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  db:
    image: postgres:16-bookworm
    container_name: memomate_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - memomate_db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-memomate_user} -d ${DB_DATABASE:-memomate_db}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  memomate_db_data:
